/* P-120 Founder Editorial Story EN v1.0
   Full English editorial counterpart to the canonical RU Founder Story.
   No assessment, scoring, report or scientific-model mutations. */
(() => {
  'use strict';
  if(!/\/en\/creator\/(?:index\.html)?$/i.test(location.pathname)) return;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const questions=[
    ['CLOSENESS','What makes me move closer?'],['DISTANCE','What makes me step back?'],['TOUCH','What does touch mean to me?'],['FREEDOM','When does freedom become distance?'],['DESIRE','What do I recognize as an expression of desire?'],['LANGUAGE','What do I expect from another person but never put into words?'],['INNER EXPERIENCE','What do I feel but still do not know how to name?']
  ];
  const doctrine=[['NOT A LABEL','BUT VISIBILITY.'],['NOT A JUDGMENT','BUT LANGUAGE.'],['NOT ONE SCORE','BUT LAYERS.'],['NOT A DEFECT','BUT DIFFERENCE.'],['NOT PROPHECY','BUT REFLECTION.'],['NOT MYSTIFICATION','BUT EVIDENCE.']];
  function markup(){return `
<section class="founder-story" id="founder-story" data-founder-story="v1.0-en" aria-labelledby="founder-story-title">
  <section class="founder-story__scene founder-story__scene--statement" id="fnd-00" data-fnd-screen="FND-00"><div class="founder-story__inner founder-story__reveal"><p class="founder-story__eyebrow">From the Creator's Notes</p><h2 class="founder-story__display" id="founder-story-title">P-120 did not begin with a test.</h2><p class="founder-story__display">It began with a question.</p></div></section>
  <section class="founder-story__scene founder-story__scene--question" id="fnd-01" data-fnd-screen="FND-01"><div class="founder-story__inner founder-story__reveal"><p class="founder-story__eyebrow">01 / The Question</p><p class="founder-story__display founder-story__display--question">Why can a person feel so much — and still have so little language for it?</p><p class="founder-story__display founder-story__display--question">Why can two people be close — and still fail to truly tell each other who they are?</p></div></section>
  <section class="founder-story__scene" id="fnd-02" data-fnd-screen="FND-02"><div class="founder-story__inner founder-story__reading founder-story__reveal"><p class="founder-story__eyebrow">02 / Life Came First</p><p>I thought about this for many years. Not as a researcher who sat down one day before a blank page and decided to create a new test.</p><p>Life came first. Relationships. Mistakes. Encounters. Separations. Periods of closeness — and years of solitude, when there is much more time to look back, compare, and ask uncomfortable questions.</p><p>I spoke with very different people — people who explain the human being through psychology, philosophy, the body, feelings, or intuition. And the more explanations I heard, the less interested I became in what a person is supposed to be.</p><p><strong>What interested me was something else: what does a person actually experience when no one is asking for the right answer?</strong></p></div></section>
  <section class="founder-story__scene" id="fnd-03" data-fnd-screen="FND-03"><div class="founder-story__inner founder-story__beats"><p class="founder-story__eyebrow founder-story__reveal">03 / Between Feeling and Language</p><p class="founder-story__beat founder-story__reveal">A person can have a feeling — but no word for it.</p><p class="founder-story__beat founder-story__reveal">Desire — but no inner permission to speak about it.</p><p class="founder-story__beat founder-story__reveal">A bodily response — but no understanding of what it means specifically for them.</p><p class="founder-story__beat founder-story__beat--final founder-story__reveal">Sometimes the distance between experience and language becomes greater than the distance between two people.</p></div></section>
  <section class="founder-story__scene" id="fnd-04" data-fnd-screen="FND-04"><div class="founder-story__inner"><p class="founder-story__eyebrow founder-story__reveal">04 / What Remains Unsaid</p><div class="founder-story__questions">${questions.map(([m,q])=>`<div class="founder-story__question-row founder-story__reveal"><span class="founder-story__marker">${esc(m)}</span><span class="founder-story__question-text">${esc(q)}</span></div>`).join('')}</div></div></section>
  <section class="founder-story__scene founder-story__scene--statement" id="fnd-05" data-fnd-screen="FND-05"><div class="founder-story__inner founder-story__reveal"><p class="founder-story__eyebrow">05 / Observation</p><p class="founder-story__display founder-story__display--insight">So much between people falls apart not because they feel nothing.</p><p class="founder-story__display founder-story__display--insight">Sometimes because they feel more than they know how to translate into words.</p><p class="founder-story__lead">Something left unsaid does not always mean concealment. Sometimes a person has not yet seen the structure of what is happening inside them.</p></div></section>
  <section class="founder-story__scene founder-story__scene--scientific" id="fnd-06" data-fnd-screen="FND-06"><div class="founder-story__inner founder-story__reveal"><div class="founder-story__rule" aria-hidden="true"></div><div class="founder-story__reading"><p>At some point another question emerged:</p><p><strong>What if, before explaining a person, we simply asked them sufficiently precise questions?</strong></p><p>Not whether they are a good partner. Not whether their desires are normal. Not who they ought to be.</p><p>But how, specifically, they experience closeness, desire, touch, initiative, safety, distance, and reciprocity.</p></div><p class="founder-story__display founder-story__display--turn" style="margin-top:clamp(54px,7vw,110px)">A philosophical question becomes a research task.</p></div></section>
  <section class="founder-story__scene founder-story__scene--scientific" id="fnd-07" data-fnd-screen="FND-07"><div class="founder-story__inner founder-story__coordinates"><div class="founder-story__coordinate-copy founder-story__reveal"><p class="founder-story__eyebrow">07 / Coordinates</p><p><strong>That is how P-120 gradually emerged.</strong></p><p>Not as a formula for a person. Not as a final verdict.</p><p><strong>As a coordinate system.</strong></p><p>Complexity does not become simple when it gains coordinates. It becomes distinguishable.</p><p>That is what interested me: not reducing a person to a result, but increasing the resolution with which they can look at their own experience.</p></div><div class="founder-story__coordinate-field founder-story__reveal" aria-hidden="true"><div class="founder-story__coordinate-labels"><span>DESIRE</span><span>CLOSENESS</span><span>DISTANCE</span><span>TOUCH</span><span>LANGUAGE</span><span>RECIPROCITY</span></div></div></div></section>
  <section class="founder-story__scene" id="fnd-08" data-fnd-screen="FND-08"><div class="founder-story__inner"><p class="founder-story__eyebrow founder-story__reveal">08 / Principles</p><div class="founder-story__doctrine">${doctrine.map(([a,b])=>`<div class="founder-story__doctrine-row founder-story__reveal"><span>${esc(a)}</span><span>${esc(b)}</span></div>`).join('')}</div></div></section>
  <section class="founder-story__scene founder-story__scene--scientific" id="fnd-09" data-fnd-screen="FND-09"><div class="founder-story__inner founder-story__boundary"><div class="founder-story__reveal"><p class="founder-story__eyebrow">09 / Where the Author Ends</p><h3 class="founder-story__boundary-title">P-120 was born from a personal and philosophical question.</h3></div><div class="founder-story__boundary-copy founder-story__reveal"><p><strong>But the system's answers must not depend on the philosophy of its creator.</strong></p><p>An observation must become a hypothesis. A hypothesis — a defined construct. Measurement — something that can be tested. And where the evidence is insufficient, the system must be able to say: “We do not know that yet.”</p><p>For me, that is not a weakness. It is the boundary between belief and knowledge.</p><p>P-120 should not read minds, “reveal the subconscious,” or determine fate. Its task is to work only within what can actually be justified.</p><button class="founder-story__science-link" type="button" data-founder-route="science">How the scientific base works →</button></div></div></section>
  <section class="founder-story__scene founder-story__scene--north" id="fnd-10" data-fnd-screen="FND-10"><div class="founder-story__inner founder-story__reveal"><p class="founder-story__eyebrow">10 / P-120 North Star</p><div class="founder-story__reading"><p>That is why the task of P-120 is at once more modest and more difficult.</p><p>Not to explain a person in their place.<br>Not to define them.<br>Not to fix them.</p><p><strong>To help them notice.</strong></p></div><p class="founder-story__display founder-story__display--north" style="margin-top:clamp(56px,7vw,120px)">Make the inner visible.</p><div class="founder-story__north-copy"><p>Sometimes the first real step toward understanding another person begins not with a conversation with them, but with the moment we have looked carefully enough at ourselves.</p></div></div></section>
  <section class="founder-story__scene" id="fnd-11" data-fnd-screen="FND-11"><div class="founder-story__inner founder-story__signature founder-story__reveal"><div><p class="founder-story__signature-mark">Di</p><p class="founder-story__signature-role">from the creator's notes · P-120</p></div><nav class="founder-story__routes" aria-label="Continue through P-120"><button class="founder-story__route" type="button" data-founder-route="self"><span>TAKE P-120 · RU</span><span aria-hidden="true">→</span></button><button class="founder-story__route" type="button" data-founder-route="science"><span>SCIENTIFIC BASE</span><span aria-hidden="true">→</span></button><button class="founder-story__route" type="button" data-founder-route="why"><span>WHY P-120?</span><span aria-hidden="true">→</span></button></nav></div></section>
</section>`}
  function install(){const main=document.querySelector('#main-content');if(!main||document.getElementById('founder-story'))return false;main.insertAdjacentHTML('beforeend',markup());const nodes=[...document.querySelectorAll('.founder-story__reveal')];if(!('IntersectionObserver'in window)){nodes.forEach(n=>n.classList.add('is-visible'))}else{const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{rootMargin:'0px 0px -7% 0px',threshold:.05});nodes.forEach(n=>io.observe(n))}document.documentElement.dataset.founderStoryEn='v1.0';return true}
  if(install())return;const mo=new MutationObserver(()=>{if(install())mo.disconnect()});mo.observe(document.documentElement,{childList:true,subtree:true});
})();
