/* P-120 Legal Publication Pages v1.0 — SANDBOX · DEC */
(() => {
  'use strict';
  const isEn=(document.documentElement.lang||'').toLowerCase().startsWith('en')||/\/en(?:\/|$)/i.test(location.pathname);
  const type=/\/intellectual-property\//i.test(location.pathname)?'ip':/\/privacy\//i.test(location.pathname)?'privacy':'terms';
  const marker='/p120-web/'; const i=location.pathname.indexOf(marker); const base=i>=0?location.pathname.slice(0,i)+marker:'/';
  const home=base+(isEn?'en/':'');
  const routes=isEn?{ip:base+'en/intellectual-property/',terms:base+'en/terms/',privacy:base+'en/privacy/'}:{ip:base+'intellectual-property/',terms:base+'terms/',privacy:base+'privacy/'};
  const counterpart=type==='ip'?(isEn?base+'intellectual-property/':base+'en/intellectual-property/'):type==='terms'?(isEn?base+'terms/':base+'en/terms/'):(isEn?base+'privacy/':base+'en/privacy/');

  const data={
    ru:{
      ip:{
        title:'Интеллектуальная собственность и условия использования',kicker:'P-120 · LEGAL / INTELLECTUAL PROPERTY',
        note:'В текущей sandbox/test среде DEC используется как обозначение правообладателя. Это не заменяет документального подтверждения цепочки прав; production gate остаётся открытым до юридической проверки.',
        meta:'Версия v1.0 · 1 сентября 2026 · Правообладатель (sandbox): DEC',
        sections:[
          ['Правообладатель и статус','Для текущей sandbox/test среды обозначенным правообладателем материалов P-120 является DEC. Указание DEC в настоящем документе является конфигурацией тестовой среды и само по себе не заменяет документального подтверждения цепочки прав. Перед production-запуском наименование правообладателя подлежит юридической проверке.'],
          ['Охраняемые материалы','В пределах, предусмотренных применимым законодательством, охрана может распространяться на оригинальные тексты и формулировки заданий, инструкции, редакционные и научные материалы, оригинальный подбор и расположение материалов, графические и интерфейсные решения, иллюстрации, отчётные формы, программный код и его конкретное выражение, документацию, переводы и иные самостоятельные творческие элементы P-120.'],
          ['Граница методологии','Настоящее уведомление не заявляет авторское право на абстрактные идеи, научные факты, концепции, принципы, методы, процессы, системы, способы или математические концепции как таковые в тех юрисдикциях, где они исключены из авторско-правовой охраны. Охрана заявляется в отношении оригинальной формы выражения, документации, подбора, расположения, реализации и иных охраноспособных элементов.'],
          ['Разрешённое использование','Пользователю предоставляется ограниченное право получить доступ к P-120 и пройти тест для личных целей, просмотреть предоставленный результат и сохранить законно предоставленный ему отчёт. Цитирование и иное использование, прямо разрешённые обязательными нормами применимого законодательства, сохраняются.'],
          ['Ограниченное использование','Без предварительного разрешения DEC, кроме случаев, когда такое ограничение недопустимо по применимому законодательству, не допускаются систематическое копирование или публикация банка заданий; автоматизированный массовый сбор материалов; создание зеркал или конкурентных копий охраняемого корпуса; коммерческое распространение; удаление уведомлений об авторских правах; извлечение закрытых scoring-материалов; использование непубличных материалов, полученных без разрешения.'],
          ['Программное обеспечение и базы данных','Программная реализация P-120 и оригинальные базы/компиляции охраняются в той степени, в какой они отвечают требованиям соответствующего законодательства. Любые отдельные права изготовителя базы данных применяются только при наличии предусмотренных законом условий и не отменяют правомерное использование и обязательные исключения.'],
          ['Непубличные материалы и know-how','Закрытые ключи, веса, калибровочные данные, внутренние scoring/decision rules, непубличный item bank и иные сведения могут защищаться как конфиденциальные материалы или know-how только пока фактически соблюдается режим ограниченного доступа и иные необходимые меры. Открытая публикация таких сведений может лишить их режима секретности.'],
          ['Бренд и обозначения','Наименование P-120, логотипы, графические обозначения и иные элементы бренда могут дополнительно охраняться законодательством о товарных знаках и недобросовестной конкуренции. Наличие настоящего copyright notice само по себе не означает регистрацию товарного знака.'],
          ['Обязательные исключения и отсутствие отказа от прав','Ничто в настоящем уведомлении не ограничивает права пользователя, которые не могут быть исключены договором или уведомлением в соответствующей юрисдикции. Неприменение DEC какого-либо права в конкретном случае не означает отказ от такого права.'],
          ['Контакт и лицензирование','Запросы на научное, образовательное, коммерческое, издательское или интеграционное использование материалов P-120 должны направляться через официальный контактный канал, указанный на сайте. До production-релиза контакт может оставаться sandbox placeholder.']
        ]
      },
      terms:{title:'Условия использования — Sandbox',kicker:'P-120 · TERMS / SANDBOX',note:'Текущая страница — контролируемый sandbox notice, а не финальные production Terms of Use.',meta:'Sandbox-публикация · не финальный production legal instrument',sections:[
        ['Статус документа','Это sandbox notice для текущей тестовой среды P-120. Полные production Terms of Use ещё не выпущены. Настоящая страница фиксирует только правила доступа и использования, необходимые для тестовой реализации, и не устанавливает отдельный выбор права, суда или арбитража.'],
        ['Личное прохождение','Доступ к assessment предоставляется для личного прохождения. Пользователь может просматривать законно предоставленный ему результат и сохранять предоставленный отчёт для личного использования.'],
        ['Интеллектуальная собственность','Использование материалов P-120 регулируется отдельным Уведомлением об интеллектуальной собственности и условиями использования. Систематическое копирование или публикация банка заданий, автоматизированный массовый сбор, коммерческое распространение и получение непубличных scoring-материалов без разрешения DEC ограничиваются в пределах, допускаемых применимым законодательством.'],
        ['Обязательные права пользователя','Ничто на этой странице не ограничивает права и исключения, которые по применимому законодательству не могут быть отменены договором или уведомлением.'],
        ['Sandbox production gate','Перед коммерческим production-запуском необходимы отдельная юридическая проверка окончательных Terms of Use, точного наименования правообладателя и связанной privacy/consumer-law архитектуры.']
      ]},
      privacy:{title:'Конфиденциальность — Sandbox',kicker:'P-120 · PRIVACY / SANDBOX',note:'Текущая страница описывает фактическую sandbox-архитектуру на высоком уровне и не заменяет финальную production Privacy Policy.',meta:'Sandbox-публикация · production privacy gate открыт',sections:[
        ['Статус документа','Это sandbox privacy notice для текущей исследовательской реализации. Полная production Privacy Policy ещё не выпущена; перед production-запуском необходима отдельная проверка применимого законодательства, роли оператора/контролёра и обязательных реквизитов.'],
        ['Идентификатор участника','Текущая web-форма использует псевдонимный Participant ID. Автоматический intake не добавляет имя, e-mail или телефон в пакет ответов.'],
        ['Ответы и служебные данные','В исследовательский пакет могут входить ответы на scored-items, версия формы, язык интерфейса, покрытие, выбранные режимы администрирования и временные отметки сессии. Текущая intake-реализация не включает telemetry в передаваемый пакет.'],
        ['Локальное хранение','Состояние текущей сессии и служебные записи, включая ответы и подтверждение legal clickwrap, могут сохраняться локально в браузере, чтобы поддерживать продолжение сессии и фиксировать принятую версию notice.'],
        ['Исследовательское хранилище','После завершения scored-items текущая sandbox-конфигурация может передавать псевдонимный пакет ответов в настроенное приватное исследовательское хранилище. Доступ со стороны браузера ограничен предусмотренным intake-путём; эта страница не утверждает, что текущая sandbox-конфигурация является финальной production privacy architecture.'],
        ['Не вводить прямые идентификаторы','Если интерфейс прямо не запрашивает персональные контактные данные, не добавляйте имя, адрес, телефон, e-mail или иные прямые идентификаторы в свободные поля или передаваемые материалы.'],
        ['Production gate','До публичного production-релиза должны быть утверждены окончательная Privacy Policy, основания и сроки обработки/хранения, процесс реализации прав субъектов данных, сведения о поставщиках/передачах и иные обязательные элементы применимого права.']
      ]}
    },
    en:{
      ip:{title:'Intellectual Property & Permitted Use',kicker:'P-120 · LEGAL / INTELLECTUAL PROPERTY',note:'In the current sandbox/test environment, DEC is used as the displayed rights-holder label. This does not replace documentary chain-of-title evidence; the production gate remains open pending legal verification.',meta:'Version v1.0 · 1 September 2026 · Rights holder (sandbox): DEC',sections:[
        ['Rights holder and status','For the current sandbox/test environment, DEC is the displayed rights-holder name for P-120 materials. This is a sandbox configuration and does not itself replace documentary confirmation of chain of title. The production rights-holder name must be legally verified before launch.'],
        ['Protected materials','To the extent protected by applicable law, protection may apply to original assessment-item wording, instructions, editorial and scientific text, original selection and arrangement of materials, visual and interface design, illustrations, report formats, software code as expressed, documentation, translations and other independently protectable creative elements of P-120.'],
        ['Methodology boundary','This Notice does not assert copyright ownership over abstract ideas, scientific facts, concepts, principles, methods, processes, systems, procedures or mathematical concepts as such where they are excluded from copyright protection. Protection is asserted over original expression, documentation, selection, arrangement, implementation and other protectable elements.'],
        ['Permitted use','Users receive a limited permission to access P-120, take the assessment for personal purposes, view the result made available to them, and retain any report lawfully provided to them. Quotation and other uses mandated or permitted by applicable law remain available.'],
        ['Restricted use','Without prior permission from DEC, and except where a restriction is unenforceable under applicable law, users may not systematically copy or publish the item bank; perform automated bulk harvesting; create mirrors or competing copies of the protected corpus; commercially redistribute protected materials; remove rights notices; obtain or disclose non-public scoring materials; or use non-public materials acquired without authorization.'],
        ['Software and databases','P-120 software implementation and original databases/compilations are protected to the extent they satisfy the requirements of applicable law. Any separate database-maker right applies only where its statutory conditions are met and remains subject to lawful-user rights and mandatory exceptions.'],
        ['Non-public materials and know-how','Private keys, weights, calibration data, internal scoring/decision rules, unpublished item banks and similar information may be protected as confidential information or know-how only while access is genuinely restricted and required confidentiality measures are maintained. Public disclosure may terminate secrecy-based protection.'],
        ['Brand identifiers','P-120 names, logos and other brand identifiers may receive separate protection under trademark and unfair-competition law. This copyright notice does not itself mean that a trademark has been registered.'],
        ['Mandatory exceptions and no waiver','Nothing in this Notice limits user rights that cannot lawfully be excluded by notice or contract in the relevant jurisdiction. A failure by DEC to enforce a right in a particular instance is not a waiver of that right.'],
        ['Licensing and contact','Requests for scientific, educational, commercial, publishing or integration use of P-120 materials should be sent through the official contact channel published on the site. Until production launch, the contact may remain a sandbox placeholder.']
      ]},
      terms:{title:'Terms of Use — Sandbox',kicker:'P-120 · TERMS / SANDBOX',note:'This page is a controlled sandbox notice, not the final production Terms of Use.',meta:'Sandbox publication · not the final production legal instrument',sections:[
        ['Document status','This is a sandbox notice for the current P-120 test environment. Full production Terms of Use have not yet been issued. This page records only the access and use rules needed for the test implementation and does not establish a separate choice of law, forum or arbitration clause.'],
        ['Personal assessment use','Access to the assessment is provided for personal use. A user may view a result lawfully made available to them and retain a provided report for personal use.'],
        ['Intellectual property','Use of P-120 materials is governed by the separate Intellectual Property & Permitted Use Notice. Systematic copying or publication of the item bank, automated bulk harvesting, commercial redistribution and obtaining non-public scoring materials without DEC authorization are restricted to the extent permitted by applicable law.'],
        ['Mandatory user rights','Nothing on this page limits rights or exceptions that applicable law does not permit to be excluded by contract or notice.'],
        ['Sandbox production gate','Before commercial production launch, the final Terms of Use, exact rights-holder identity and related privacy/consumer-law architecture require separate legal review.']
      ]},
      privacy:{title:'Privacy — Sandbox',kicker:'P-120 · PRIVACY / SANDBOX',note:'This page describes the current sandbox architecture at a high level and does not replace the final production Privacy Policy.',meta:'Sandbox publication · production privacy gate remains open',sections:[
        ['Document status','This is a sandbox privacy notice for the current research implementation. A full production Privacy Policy has not yet been issued; applicable law, controller/operator roles and mandatory disclosures require separate review before production launch.'],
        ['Participant identifier','The current web form uses a pseudonymous Participant ID. The automatic intake does not add a name, e-mail address or phone number to the response package.'],
        ['Responses and operational data','The research package may include scored-item responses, form version, interface locale, coverage, selected administration modes and session timestamps. The current intake implementation does not include telemetry in the transmitted package.'],
        ['Local storage','Current-session state and operational records, including responses and the legal clickwrap record, may be stored locally in the browser to support session continuity and record the accepted notice version.'],
        ['Research storage','After completion of the scored items, the current sandbox configuration may transmit a pseudonymous response package to the configured private research store. Browser-side access is constrained to the configured intake path; this page does not claim that the sandbox configuration is the final production privacy architecture.'],
        ['Do not add direct identifiers','Unless the interface expressly asks for personal contact data, do not add your name, address, phone number, e-mail address or other direct identifiers to free-text fields or transmitted materials.'],
        ['Production gate','Before public production release, the final Privacy Policy, processing/storage grounds and retention, data-subject rights workflow, provider/transfer disclosures and other mandatory elements of applicable law must be approved.']
      ]}
    }
  };
  const d=data[isEn?'en':'ru'][type];
  document.title=d.title+' — P-120';
  const root=document.querySelector('[data-p120-legal-page-root]')||document.body;
  const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  root.innerHTML=`<header class="p120-legal-page__topbar"><div class="p120-legal-page__topbar-inner"><a class="p120-legal-page__brand" href="${home}">P-120</a><span class="p120-legal-page__badge">LEGAL · SANDBOX · v1.0</span><nav class="p120-legal-page__lang" aria-label="Language"><a href="${counterpart}">${isEn?'RU':'EN'}</a></nav></div></header><main class="p120-legal-main"><section class="p120-legal-hero"><div><div class="p120-legal-kicker">${esc(d.kicker)}</div><h1>${esc(d.title)}</h1></div><div class="p120-legal-hero__meta">${esc(d.meta)}</div></section><aside class="p120-legal-sandbox-note">${esc(d.note)}</aside><div class="p120-legal-sections">${d.sections.map((s,n)=>`<section class="p120-legal-section"><div class="p120-legal-section__num">${String(n+1).padStart(2,'0')}</div><div><h2>${esc(s[0])}</h2><p>${esc(s[1])}</p></div></section>`).join('')}</div><nav class="p120-legal-related" aria-label="${isEn?'Related legal information':'Связанная правовая информация'}"><a href="${routes.ip}">${isEn?'Intellectual Property':'Интеллектуальная собственность'}</a><a href="${routes.terms}">${isEn?'Terms of Use':'Условия использования'}</a><a href="${routes.privacy}">${isEn?'Privacy':'Конфиденциальность'}</a><a href="${home}">${isEn?'Return to P-120':'Вернуться к P-120'}</a></nav></main>`;
})();
